server:
  port: 8334

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_SCHEMA_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  security:
#    user:
#      name: admin
#      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

alertsystem:
  app:
    secret: ${JWT_SECRET}
    expirationMs: ${JWT_EXPIRE}

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth/swagger-ui.html

openapi:
  service:
    title: Authentication API specification
    version: 1.0.0
    url: https://localhost:8443