openapi:
  service:
    title: Test-service API specification
    version: 1.0.0
    url: https://localhost:8443

spring:
  application:
    name: test-service

server:
  port: 8996

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    enabled: true
    path: /${spring.application.name}/swagger-ui.html




